### ISSUE TITLE
Composer support (fuelphp/fuelphp in packagist)

### ISSUE THREAD

**Issue by dario1985** [fuelphp/fuelphp#49]
I didn't found the composer package "fuelphp/fuelphp" (as defined in composer.json), it would be easier to include and to test if it was included in packagist.org.

**Comment by sagikazarmark** [comment]
I think `fuelphp/fuelphp` is already added, isn't it?

**Comment by stevewest** [comment]
yes https://packagist.org/packages/fuelphp/fuelphp
