### ISSUE TITLE
Logging::write() custom levels being converted to int

### ISSUE THREAD

**Issue by casperwilkes** [fuelphp/fuelphp#60]
In the documentation it states that you can use <code>Log::write()</code> to create you're own custom levels to log at. 
```php
// and finally, we create a log entry with a custom $level
Log::write('Link', 'More info on http://fuelphp.com/')
```

This does not work as of the current version. Currently, it's taking your custom level, checking against an array of predefined settings, if not found, and converting it to a notice. If you use leave the default threshold where it's set in the config file, the NOTICE threshold is too small, thus not getting logged.

This kind of defeats the purpose if you want to use your own levels. If you lower the threshold as a work around, you have get a lot of unnecessary logging going on from the router class. 

Please see: Fuel/Core/Classes/Log.php line 222:
```php
if (is_string($level))
		{
			if ( ! $level = array_search($level, static::$levels))
			{
				$level = 250;	// can't map it, convert it to a NOTICE
			}
		}
```

**Comment by sagikazarmark** [comment]
Are you sure this is the correct repository for this issue? Isn't it a v1 core issue?

Also, please provide better references: link to the line or at least a correct file path.

**Comment by stevewest** [comment]
This is the wrong repo. Please reopen this issue at https://github.com/fuel/core
