### ISSUE TITLE
Question: I have some problems in ORM

### ISSUE THREAD

**Issue by musou1500** [fuelphp/fuelphp#61]
I wrote a model and some controller code below.
```php
class Model_news extends Orm\Model {
  // some relations
}
```
```php
namespace Controller;
class Api extends \Controller_Rest{
  public function get_news() {
    $news = \Model_News::find('all', ['related'=> ['user', 'tags']]);
    return $this->response($news);
  }
}
```

First, `find` method return dictionary.
This dictionary have key as a primary key's value.
But, I want to get normal array(key is a sequential number).
Can I switch a fetch mode someway?

Second, in model collection(find method returns) contains `string` value inspite of mysql field type is `int`.
at last,
`return $this->response($news);`
this code shows json to client, but `$to_array_exclude` not affect to 'user' ot 'tags' relation.

Sorry for my terrible english.
Thank you.

**Comment by stevewest** [comment]
You have the wrong repo, this is relating to the v1 orm which is found at https://github.com/fuel/orm

You first question can be solved with `array_values()`

The second can be solved with the Typing observer http://fuelphp.com/docs/packages/orm/observers/included.html#os_typing

**Comment by stevewest** [comment]
Sorry, and for your third question, at the moment you have to call `->to_array()` on each model for `$_to_array_exclude` to have any effect, it is a bug in the current code that has not been solved yet.

**Comment by musou1500** [comment]
Thank you.
about first question, fuelphp does not have a setting options for this?

**Comment by stevewest** [comment]
No, it does not.

**Comment by musou1500** [comment]
Thank you.
I'll try solution that using `array_value`.
