### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by Alphapixels** [fuelphp/fuelphp#62]
Hey,

I'm looking into using Fuel for a large application and I'm wondering if it still is actively maintained.

Cheers!

**Comment by sagikazarmark** [comment]
Yes it is actively maintained. Fuel v2 is already in alpha state, so not recommended for production. In the next few weeks I am going to spend some times with foundation, routing and framework internals.

**Comment by WanWizard** [comment]
That that the current version can be found at https://github.com/fuel
