### ISSUE TITLE
Fuelphp simplified Chinese Manual － FuelPHP简体中文手册

### ISSUE THREAD

**Issue by wxb** [fuelphp/fuelphp#63]
@stevewest @sagikazarmark 

## simplified Chinese Manual
Hi, I translated this site [www.fuelphp.com](http://www.fuelphp.com/) into Chinese (Simplified), Can you create a link in Chinese (Simplified) , This can help Chinese developers

## 简体中文手册
本手册是本人在使用fuelPHP中，由于原有fuelPHP官网使用了一些google的jQuery，导致网页加载慢甚至无法加载。自己download了官网， 修改了其中jQuery加载的url，同时针对繁体中文对于很多人来说阅读还是有一些费劲，所以利用业余时间逐步翻译成简体中文。分享给大家， 希望可以帮到想要了解fuelPHP的小伙伴么！

## 手册地址
[中文手册](http://wxb.github.io/fuelPHP.zh-CN/index.html)
[中文手册GitHub](https://github.com/wxb/fuelPHP.zh-CN)

## 状态
简直中文正在翻译中，欢迎对fuelphp感兴趣的小伙伴加入 :smile:

**Comment by WanWizard** [comment]
You're posting to the wrong repo, can you please re-open it at http://github.com/fuel/docs/issues ?

**Comment by wxb** [comment]
:sweat_smile:  I'm sorry! Thanks @WanWizard
