### ISSUE TITLE
Dots in parameters

### ISSUE THREAD

**Issue by Eredrim** [fuelphp/fuelphp#67]
When I pass parameters with dots (GET), the last substring is removed when I get back the variable in my controller function.

For example, if I pass the email address hello.sir@gmail.com as a parameter => controller/function/hello.sir@gmail.com, I just receive the string 'hello.sir@gmail' in my function.

**Comment by axelitus** [comment]
I'm guessing it does not matter how many dots there are (from 1 to n) this seems to be an "extension stripping" issue. ¿Does this happen also with one dot?

**Comment by Eredrim** [comment]
Yes, the issue is the same with just one dot. If you pass 'aaaa.bbbb', you get back only 'aaaa'.

**Comment by stevewest** [comment]
This has been opened on the wrong repository, please use https://github.com/fuel/core

**Comment by axelitus** [comment]
The issue follow-up is here: https://github.com/fuel/core/issues/2002
