### ISSUE TITLE
Get groups from simpleAuth config

### ISSUE THREAD

**Issue by des1roer** [fuelphp/fuelphp#71]
how i can get and set groups for auth?

**Comment by stevewest** [comment]
Please stop asking questions on the bug tracker. For one you are on the wrong repo. Second github issues are better suited to bugs and more technical questions. As @sagikazarmark has already told you please use the forums/IRC/stackoverflow/google. You can also check the official documentation which should cover all your basic questions http://fuelphp.com/docs/

**Comment by des1roer** [comment]
'm sorry, I certainly ruded . but I am not from an English-speaking country. I read all the documentation had not yet. but on the Google stack badly. there is now the FTC brought the documentation, can be used. about your little framework where you can hear. I want to promote it in their own country and then a block. unless it is impossible to write 
$groups = Auth::group()->groups();
foreach ($groups as $key => $value) {
    $arr[$value] = Auth::group('Simplegroup')->get_name($value);
}

var_dump($arr);

. no offense if the information was in the public domain would not have tortured
