### ISSUE TITLE
set my array to view

### ISSUE THREAD

**Issue by des1roer** [fuelphp/fuelphp#72]
i have 

    public function action_index() {
        $data['users'] = Model_User::find('all');

        $people = array(
            array(
                "id" => 100,
                "username" => 21
            ),
            array(
                "id" => -1,
                "username" => 23
            )
        );
        $view = View::forge('admin/users/index', $data);

        $view->set_global('users', Arr::assoc_to_keyval($people, 'group', 'username'));
        $this->template->title = "Users";

        $this->template->content = $view;
    }

not work

**Comment by sagikazarmark** [comment]
@des1roer I am asking you again, please stop using the issue tracker for help. This is not the correct channel for that, not even the correct repository.

**Comment by des1roer** [comment]
what is corect way? when i ask in SO i`m banned

**Comment by sagikazarmark** [comment]
You can use IRC: http://fuelphp.com/contact
You can use the forum: http://fuelphp.com/forums/

I understand that you need help and you are not a fluent English speaker, but the problem with the above question is that it's not a question: what does not work? What happens? What would you like to achieve?

**Comment by des1roer** [comment]
public function action_index() {
        $data['users'] = Model_User::find('all');

        $people = array(
            array(
                "group" => 100,
                "username" => 21
            ),
            array(
                "group" => -1,
                "username" => 23
            )
        );
        $view = View::forge('admin/users/index', $data);

        $view->set_global('users', Arr::assoc_to_keyval($people, 'group', 'username'));
        
        $this->template->title = "Users";

        $this->template->content = $view;
    }

i wonna not '100'  i wonna 'Administrators' in row

**Comment by stevewest** [comment]
@des1roer As @sagikazarmark has already stated this is not the channel for such discussion. Please use the correct repo, IRC or the forums.
