### ISSUE TITLE
maybe gitter for ask?

### ISSUE THREAD

**Issue by des1roer** [fuelphp/fuelphp#73]
irc not work. in forum i don`t add ask

**Comment by stevewest** [comment]
Please stop spamming the issue tracker.

**Comment by sagikazarmark** [comment]
Come on, it is really not that hard:

https://kiwiirc.com/client

1. Choose a nickname
2. Enter `fuelphp` into the channel

What's your problem with the forum?

Please try to understand our point of view: we are willing to help you on the correct channels.
