### ISSUE TITLE
I can not configure the database, what do I do?

### ISSUE THREAD

**Issue by BackR** [fuelphp/fuelphp#79]
The page returns this error (I'm using the 1.7 version):

>Fuel\Core\Database_Exception [ 1045 ]:
>SQLSTATE[HY000] [1045] Access denied for user '**********'@'localhost' (using password: YES)

The file indicated by the error is: **fuel/core/classes/database/pdo/connection.php @ line 112:**

`throw new \Database_Exception(str_replace($this->_config['connection']['password'], str_repeat('*', 10), $e->getMessage()), $error_code, $e);`

My code for database connection is this:

    return array(
	    'default' => array(
		    'connection'  => array(
		    	    'dsn'        => 'mysql:host=localhost;dbname=fuelphp',
			    'username'   => 'root',
			    'password'   => '',
		    ),
	    ),
    );

My Model is this:

    namespace Model;

    use Fuel\Core\DB;

    class Welcome extends \Model
    {
    public static function get_results()
    {
        DB::query('SELECT * FROM cliente');
    }
    }

And my code for Controller is this:
    
    use \Model\Welcome;

    class Controller_Welcome extends Controller
    {
    public function action_index()
    {
        $results = Welcome::get_results();
    }
    }

Can someone help me?

*I'm sorry if this is not the right place for this purpose, I'm starting on GitHub ... Thanks in advance.*

Signed, Ricardo Back

**Comment by stevewest** [comment]
It looks like you have not set up your DBMS up correctly, this is not a fuel issue. Make sure you check the username and password are correct and that the user has the correct permissions.

This is also the wrong repo, this one is for v2, you want https://github.com/fuel/fuel
