### ISSUE TITLE
sqlsrv driver connection error

### ISSUE THREAD

**Issue by salipro4ever** [fuelphp/fuelphp#80]
I got this error although i am using on Windows 10
**The "SQLSRV" database driver works only on Windows. On nix, use the "DBLib" driver instead.**

This problem here:
`if (php_uname('s') !== 'Windows')`
on Windows 10, php_uname() returned "Windows NT".

Pls fix that asap

**Comment by emlynwest** [comment]
I think you have the wrong repo. I suspect you're looking for fuel/core or possibly fuelphp/database.
