### ISSUE TITLE
filetype(): Lstat failed

### ISSUE THREAD

**Issue by cinemaforay** [fuelphp/fuelphp#81]
Please refer to the following discussion.
https://fuelphp.com/forums/discussion/comment/11037
The issue is five years old, but it has not been resolved yet.

**Comment by WanWizard** [comment]
How can it be reproduced? I never got a response on what caused it, and none of our applications, and none of our clients applications have it.

**Comment by WanWizard** [comment]
p.s. you've created this issue in the wrong repo, please re-create it in https://github.com/fuel/core/issues.
