### ISSUE TITLE
Problem collisions with Event of PHP libevent extension.

### ISSUE THREAD

**Issue by vanht** [fuelphp/fuelphp#82]
I build [RatchetPHP](http://socketo.me/docs/deploy) and install [event extension](http://php.net/manual/en/book.event.php), But conflict with fuelphp core Event.
I can't config run Event of FuelPHP and Event of PHP extension.

Ratchetphp: http://socketo.me/docs/deploy
event extentsion: https://pecl.php.net/package/event

**Comment by WanWizard** [comment]
Not very handy of Ratchat to create classes in the global namespace, collisions are always possible.

You can try not to use the global version for Fuel's class, but the namespaced one: \Fuel\Core\Event.

**Comment by vanht** [comment]
I don't use \Fuel\Core\Event, but in Fuel core in file /core/classes/fuel.php line 192 error.
`\Event::register('fuel-shutdown', 'Fuel::finish');`
Can you any ideas help me?
Thank you.

**Comment by WanWizard** [comment]
Hmm... Yes, the framework itself uses it too. 

The only thing you can do is search the core code for "\Event::" (there are more than only this line, and change each one to "\Fuel\Core\Event::". And keep track of this when you upgrade Fuel, and hope Rachet starts using namespaces like the rest of the world...
